#!/bin/sh
# This is a port of the Argon One install script.
# Ported by Patrick Kane
# https://github.com/freebootin/freebsd-argon

argon_create_file() {
  if [ -f "$1" ]; then 
    sudo rm "$1"
  fi
  sudo touch "$1"
  sudo chmod 666 "$1"
}

argon_check_pkg() {
  RESULT=$(pkg query %n | grep -F -w "$1")
  if [ "${RESULT}" = "" ]; then
    echo "NG"
  else
    echo "OK"
  fi
}

# TODO: Here in the original script packages were installed to handle GPIO, SMbus, and i2c.
# Those packages don't exist in FreeBSD. Instead look to use code from these repos 
# to emulate their functionality.
# https://github.com/gonzoua/freebsd-gpio
# https://github.com/evadot/fbsd_gpio_py


# TODO: Run configurations that 'raspi-config` would normally do.
# Needed settings:
# raspi-config nonint do_i2c 0
# raspi-config nonint do_serial 2
#
# This will probably have to be extracted from `raspi-config` and de-linuxized.
# https://github.com/asb/raspi-config/blob/master/raspi-config
